-- Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as total_revenue from customers group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount from customers where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customers);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating),2) from customers group by item_purchased order by avg(review_rating) desc limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,round(avg(purchase_amount),2) from customers group by shipping_type having shipping_type in ('Express','Standard');

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
select subscription_status,round(avg(purchase_amount),2),sum(purchase_amount) as total_revenue from customers group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,round(sum(case when discount_applied='Yes' then 1 end )*100.0/count(*),2) as per from customers group by item_purchased 
order by per desc limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
select 'First' as category,count(customer_id) as total from customers where previous_purchases=1
union
select 'Returning' as category,count(customer_id) as total from customers where previous_purchases between 2 and 10
union
select 'Loyal' as category,count(customer_id) as total from customers where previous_purchases>10;

-- Q8. What are the top 3 most purchased products within each category? 
select category,item_purchased,total_cus from (select category,item_purchased,
count(customer_id) as total_cus,row_number() over (partition by category order by 
count(customer_id) desc ) as rw from customers group by category,item_purchased) sub where sub.rw<=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select 'Repeat' as category,round(sum(case when subscription_status='Yes' then 1 else 0 end)*100.0/count(*),2) as
 total from customers where previous_purchases>5;
 
 -- Q10. What is the revenue contribution of each age group?  
 select age_group,sum(purchase_amount) as total_revenue from customers group by age_group order by total_revenue desc;